apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-backend
spec:
  replicas: 2
  strategy:                  # ¡Nueva sección agregada!
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1           # Máximo de pods adicionales durante la actualización
      maxUnavailable: 0     # Cero pods inactivos durante el update (0 downtime)
  selector:
    matchLabels:
      app: recommender
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
      - name: backend
        image: hiderbrandon/recommender-app:latest
        ports:
        - containerPort: 8080 
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: API_KEY
          - name: DB_HOST
            value: "cockroachdb"
          - name: DB_PORT
            value: "26257"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: ""
          - name: DB_NAME
            value: "stocks"
          - name: SSL_MODE
            value: "disable"
          - name: API_URL
            value: "https://8j5baasof2.execute-api.us-west-2.amazonaws.com/production/swechallenge/list"
          - name: APP_PORT
            value: "8080"
          - name: FRONTEND_URL
            value: "http://localhost:5173"


